// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using MyFinances.Database;

#nullable disable

namespace MyFinances.Migrations
{
    [DbContext(typeof(TransactionContext))]
    [Migration("20250313011853_CategoriesSeed-NameFix")]
    partial class CategoriesSeedNameFix
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "9.0.2");

            modelBuilder.Entity("MyFinances.Models.Categories", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("Type")
                        .HasColumnType("INTEGER");

                    b.HasKey("ID");

                    b.ToTable("Categories");

                    b.HasData(
                        new
                        {
                            ID = 1,
                            Name = "Wynagrodzenie",
                            Type = 1
                        },
                        new
                        {
                            ID = 2,
                            Name = "Inne przychody",
                            Type = 1
                        },
                        new
                        {
                            ID = 3,
                            Name = "Stypendia",
                            Type = 1
                        },
                        new
                        {
                            ID = 4,
                            Name = "Płatności",
                            Type = 0
                        },
                        new
                        {
                            ID = 5,
                            Name = "Codzienne wydatki",
                            Type = 0
                        },
                        new
                        {
                            ID = 6,
                            Name = "Jedzenie",
                            Type = 0
                        },
                        new
                        {
                            ID = 7,
                            Name = "Auto i transport",
                            Type = 0
                        },
                        new
                        {
                            ID = 8,
                            Name = "Osobiste",
                            Type = 0
                        },
                        new
                        {
                            ID = 9,
                            Name = "Podróże i wypoczynek",
                            Type = 0
                        },
                        new
                        {
                            ID = 10,
                            Name = "Rozrywka",
                            Type = 0
                        },
                        new
                        {
                            ID = 11,
                            Name = "Nauka",
                            Type = 0
                        },
                        new
                        {
                            ID = 12,
                            Name = "Inne wydatki",
                            Type = 0
                        });
                });

            modelBuilder.Entity("MyFinances.Models.Transactions", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<double>("Amount")
                        .HasColumnType("REAL");

                    b.Property<int>("CategoriesID")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("Date")
                        .HasColumnType("TEXT");

                    b.Property<int>("UsersID")
                        .HasColumnType("INTEGER");

                    b.HasKey("ID");

                    b.HasIndex("CategoriesID");

                    b.HasIndex("UsersID");

                    b.ToTable("Transactions");
                });

            modelBuilder.Entity("MyFinances.Models.Users", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Login")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("ID");

                    b.HasIndex("Email")
                        .IsUnique();

                    b.HasIndex("Login")
                        .IsUnique();

                    b.ToTable("Users");
                });

            modelBuilder.Entity("MyFinances.Models.Transactions", b =>
                {
                    b.HasOne("MyFinances.Models.Categories", "Category")
                        .WithMany("Transactions")
                        .HasForeignKey("CategoriesID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("MyFinances.Models.Users", null)
                        .WithMany()
                        .HasForeignKey("UsersID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Category");
                });

            modelBuilder.Entity("MyFinances.Models.Categories", b =>
                {
                    b.Navigation("Transactions");
                });
#pragma warning restore 612, 618
        }
    }
}
